name: MusicCollab
options:
  bundleIdPrefix: com.musiccollab
  deploymentTarget:
    iOS: 15.0

settings:
  base:
    DEVELOPMENT_TEAM: YOUR_TEAM_ID # Replace with your Apple Developer Team ID

targets:
  MusicCollab:
    type: application
    platform: iOS
    sources:
      - path: Sources
    settings:
      base:
        INFOPLIST_FILE: Sources/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.musiccollab.app
    dependencies:
      - package: Alamofire
      - package: firebase-ios-sdk
      - package: AudioKit
    info:
      path: Sources/Resources/Info.plist
      properties:
        CFBundleName: Music Collab
        CFBundleDisplayName: Music Collab
        CFBundleShortVersionString: 1.0.0
        CFBundleVersion: 1
        UILaunchStoryboardName: LaunchScreen
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        NSMicrophoneUsageDescription: "We need access to your microphone to record audio."
        NSPhotoLibraryUsageDescription: "We need access to your photos to set your profile picture." 